### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by deepak9655** [AngelSecurityTeam/Cam-Hackers#20]
![Screenshot_20201229_035010](https://user-images.githubusercontent.com/76709834/103246294-fe8d8700-4988-11eb-9859-0989bbe0e55d.png)
This error is occuring

**Comment by zaw-beep** [comment]
facebook hack tool Please tell, whats the story of them big puppys .....ကျွန်ုပ်၏ Huawei မိုဘိုင်းမှ ပို့ပါ-------- မူရင်းမက်ဆေ့ခ်ျ --------အကြောင်းအရာ၊ [AngelSecurityTeam/Cam-Hackers] Python error (#20) မှ၊ deepak9655  သို့၊ AngelSecurityTeam/Cam-Hackers CC: Subscribed 

This error is occuring

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AngelSecurityTeam/Cam-Hackers/issues/20",
"url": "https://github.com/AngelSecurityTeam/Cam-Hackers/issues/20",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Special-Esmit** [comment]
pip(3,2) install colorama
or download library !
test: 
`pip3 install colorama ; pip2 install colorama`

**Comment by Special-Esmit** [comment]
pip(3,2) install colorama
or download library !
test:
`pip3 install colorama ; pip2 install colorama`
`python -m pip install colorama`
